# 线上配置文件
# @author shing
server:
  port: 8101
  shardingsphere:
      #数据源配置
      datasource:
        # 多数据源以逗号隔开即可
        names:  my_db
        my_db:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://localhost:3306/my_db?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&characterEncoding=utf8
          username: root
          password: 123456
      # 规则配置
      rules:
        sharding:
          # 分片算法配置
          sharding-algorithms:
            # 自定义分片规则名
            answer-table-inline:
              ## inline 类型是简单的配置文件里面就能写的类型，其他还有自定义类等等
              type: INLINE
              props:
                algorithm-expression: user_answer_$->{appId % 2}
          tables:
            user_answer:
              actual-data-nodes: my_db.user_answer_$->{0..1}
              # 分表策略
              table-strategy:
                standard:
                  sharding-column: appId
                  sharding-algorithm-name: answer-table-inline
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
